#!/usr/bin/env ruby
# This command will automatically be run when you run "rails" with Rails 3 gems installed from the root of your application.

# Preliminary setup to take care of wepic-specific options and switches.
root = File.expand_path('../../',  __FILE__)
require "#{root}/lib/wl_setup"
WLSetup.parse(ARGV)

# Regular rails script 
APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path('../../config/boot',  __FILE__)
require 'rails/commands'